/* rempler le le table login */
INSERT INTO login(email , password) VALUES('mhmdeouhnan60@gmail.com' , 'mhmde0603');
    /* Exécuter */

/* rempler le le table continent */
INSERT INTO continent(nom) VALUES('Africa');


/* rempler le le table pays */
INSERT INTO pays(nom , population, langues, id_continent)
VALUES
('Maroc', '37000000', 'Arabe, Amazighe', 1),
('Tunisie', '12000000', 'Arabe', 1),
('Algérie', '45000000', 'Arabe, Tamazight', 1),
('Égypte', '110000000', 'Arabe', 1),
('Soudan', '45000000', 'Arabe', 1),
('Somalie', '17000000', 'Arabe, Somali', 1),
('Comores', '850000', 'Arabe, Comorien', 1),
('Mauritanie', '4500000', 'Arabe', 1),
('Nigeria', '220000000', 'Hausa, Yoruba, Igbo', 1),
('Afrique du Sud', '60000000', 'Afrikaan, Zoulou, Xhosa', 1),
('Kenya', '55000000', 'Kiswahili', 1),
('Éthiopie', '120000000', 'Oromo, Tigrigna', 1),
('Ghana', '35000000', 'Twi', 1),
('RD Congo', '90000000', 'Lingala, Kikongo', 1),
('Togo', '8500000', 'Ewe', 1),
('Sénégal', '17000000', 'Wolof', 1);

/* rempler de la table ville */

INSERT INTO ville(nom, description, type, id_pays)
VALUES 
('Sfax', 'Centre économique majeur et deuxième ville la plus peuplée du pays.','Principale', 2),
('Tangiers', 'Ville portuaire stratégique, proche de l\'Europe, réputée pour son histoire internationale.','Principale', 1),
('Mekele','Ville du Tigré, centre historique et commercial.','Principale', 12),
('Casablanca', 'Principal port du pays et centre économique majeur.', 'Principale', 1),
('Rabat', 'Rabat est la capitale administrative du Maroc, située sur la côte atlantique. Elle est aussi un centre politique et économique.', 'Capitale', 1),
('Alger', 'Alger est la capitale et la plus grande ville du pays, située sur la mer Méditerranée. C\'est un centre politique, économique et culturel.','Capitale', 3),
('Oran', 'Deuxième ville du pays, importante pour son port et son développement économique.','Principale', 3),
('Zouérat','Ville minière située dans le nord du pays, près des mines de fer.','Principale', 8),
('Agadir', 'Ville balnéaire située sur la côte atlantique, un centre touristique important.','Principale', 1),
('Addis-Abeba', 'Addis-Abeba est la capitale de l\'Éthiopie, un centre politique, diplomatique et économique important de l\'Afrique.','Capitale', 12),
('El-Obeid','Ville importante pour l\'agriculture et le commerce.','Principale', 5),
('Constantine', 'Ville historique, réputée pour ses ponts et son patrimoine culturel.','Principale', 3),
('Marrakech', 'Ville touristique emblématique avec une médina classée au patrimoine mondial de l\'UNESCO.', 'Principale', 1),
('Alexandrie', 'Ville portuaire, un important centre commercial et culturel méditerranéen.','Principale', 4),
('Gizeh', 'Célèbre pour ses pyramides et ses sites antiques.','Principale', 4),
('Luxor', 'Ville historique, avec des temples antiques et la Vallée des Rois.Port-Saïd : Ville portuaire située à l\'entrée du canal de Suez.','Principale', 4),
('Omdurman', 'Deuxième ville du pays, historiquement un centre islamique important.','Principale', 5),
('Port Harcour','Ville portuaire clé dans l\'industrie pétrolière du Nigeria.','Principale', 9),
('Sousse', 'Ville côtière célèbre pour ses plages et son patrimoine historique.','Principale', 2),
('Tlemcen', 'Ville historique avec un riche patrimoine culturel et architectural.','Principale', 3),
('Chindini', 'Petite ville située sur l\'île de Mohéli.','Principale', 7),
('Johannesburg','Plus grande ville du pays, centre économique et financier majeur.','Principale', 10),
('Eldoret','Ville importante dans la région agricole, un centre de commerce.','Principale', 11),
('Nairobi', 'Nairobi est la capitale et la plus grande ville du Kenya, un centre économique et politique majeur de l\'Afrique de l\'Est.','Capitale', 11),
('Lomé', 'Capitale du Togo et principale ville du pays, centre économique et politique.', 'Capitale', 15),
('Kairouan', 'Ville religieuse importante, considérée comme l\'une des plus anciennes villes islamiques du Maghreb.','Principale', 2),
('Kano','Ville historique et économique importante du nord du pays.','Principale', 9),
('Gondar','Ville historique, connue pour ses châteaux et son rôle dans l\'histoire de l\'Éthiopie.','Principale', 12),
('Port Elizabeth','Ville portuaire sur la côte sud, un centre industriel important.','Principale', 10),
('Tunis', 'Tunis est la capitale politique et économique de la Tunisie, avec un riche patrimoine historique, notamment la médina.','Capitale', 2),
('Mitsamiouli', 'Ville située sur l\'île de Grande Comore, un centre économique local.','Principale', 7),
('Dakar', 'Capitale du Sénégal, ville portuaire et centre économique du pays.', 'Capitale', 16),
('Bossaso', 'Ville portuaire et centre économique de la région de Puntland.','Principale', 6),
('Domoni', 'Ville de l\'île d\'Anjouan, un centre historique et commercial.','Principale', 7),
('Bizerte', 'Port stratégique et une des plus anciennes villes du pays.','Principale', 2),
('Boutilimit','Ville située au centre du pays, un important centre administratif.','Principale', 8),
('Nabeul', 'Ville côtière réputée pour ses poteries et son artisanat.','Principale', 2),
('Atakpamé', 'Ville située dans les montagnes de l’Altiplano, capitale de la région de l’Oti.', 'Principale', 15),
('Port-Soudan', 'Ville portuaire sur la mer Rouge, un centre économique majeur.','Principale', 5),
('Lagos','La plus grande ville du Nigeria, un centre commercial et financier majeur.','Principale', 9),
('Pretoria', 'Pretoria est la capitale administrative de l\'Afrique du Sud, située dans la province de Gauteng. Elle est le siège du gouvernement.','Capitale', 10),
('Kisumu','Ville située au bord du lac Victoria, un important centre commercial et industriel.','Principale', 11),
('Abuja', 'Abuja est la capitale fédérale du Nigeria, située au centre du pays. Elle a été choisie comme capitale en raison de sa position centrale.','Capitale', 9),
('Le Cap','Ville portuaire et centre touristique important, ainsi que le siège du Parlement.','Principale', 10),
('Kinshasa', 'Capitale et plus grande ville du pays, centre politique, économique et culturel du pays.', 'Capitale', 14),
('Diorbel', 'Ville située au centre du pays, capitale de la région du Baol.', 'Principale', 16),
('Fès', 'Ville historique, connue pour sa médina et ses anciennes écoles coraniques.','Principale', 1),
('Sokodé', 'Deuxième ville du Togo, capitale de la région de Tchaoudjo, centre commercial et culturel.', 'Principale', 15),
('Galkayo', 'Ville importante dans le centre de la Somalie, avec un rôle stratégique.','Principale', 6),
('Hawassa','Ville au bord du lac Hawassa, importante pour l\'agriculture et le tourisme.','Principale', 1),
('Durban','Ville portuaire clé sur la côte est, avec une grande population indienne.','Principale', 10),
('Nouakchott', 'Nouakchott est la capitale de la Mauritanie, située sur la côte atlantique. Elle est le principal centre administratif et commercial.','Capitale', 8),
('Blid', 'Ville au pied du Djurdjura, connue pour son agriculture.','Principale', 3),
('Atar','Ville historique du désert du Sahara, importante pour le commerce.','Principale', 8),
('Baidoa', 'Ville au sud du pays, capitale régionale de la région du Bay.','Principale', 6),
('Kumasi', 'Ville historique et capitale de la région Ashanti, centre commercial important.', 'Principale', 13),
('Thika','Ville industrielle près de Nairobi, avec une grande activité textile.','Principale', 11),
('Goma', 'Ville frontalière au Rwanda, centre économique et touristique important de l’est.', 'Principale', 14),
('Moroni', 'Moroni est la capitale des Comores, située sur l\'île de Grande Comore, avec une économie principalement axée sur la pêche et l\'agriculture.','Capitale', 7),
('Mombasa','Ville portuaire sur la côte de l\'océan Indien, un centre commercial majeur.','Principale', 11),
('Bloemfontein','Capitale judiciaire de l\'Afrique du Sud, située dans le centre du pays.','Principale', 10),
('Ibadan','Ancienne capitale de l\'État de l\'Ouest, un centre d\'enseignement et de commerce.','Principale', 9),
('Khartoum', 'Khartoum est la capitale du Soudan, située à la confluence du Nil Bleu et du Nil Blanc. C\'est le centre politique et économique du pays.','Capitale', 5),
('Sekondi', 'Ville portuaire importante et ville jumelle de Takoradi dans la région occidentale.', 'Principale', 13),
('Kiffa','Ville du sud, capitale de la région de la Wilaya de la Kaédi.','Principale', 8),
('Nyala', 'Ville située dans le Darfour, un centre économique et administratif régional.','Principale', 5),
('Jimma','Ville située dans le sud de l\'Éthiopie, importante pour l\'agriculture, notamment le café.','Principale', 12),
('Takoradi', 'Ville portuaire située dans la région occidentale, centre de l’industrie pétrolière.', 'Principale', 13),
('Nakuru','Ville du Rift Valley, connue pour son parc national et ses ressources agricoles.','Principale', 11),
('Kisangani', 'Ville située à l’est du pays, un important carrefour commercial et culturel.', 'Principale', 14),
('Saint-Louis', 'Ancienne capitale coloniale, grande ville historique et culturelle du pays.', 'Principale', 16),
('Mogadiscio', 'Mogadiscio est la capitale et la plus grande ville du pays, située sur la côte de l\'océan Indien. C\'est le principal centre administratif et commercial.','Capitale', 6),
('Mbuji-Mayi', 'Ville capitale de la province du Kasai-Oriental, centre commercial et minier.', 'Principale', 14),
('Nouadhibou','Ville portuaire importante, située au nord-ouest du pays.','Principale', 8),
('Lubumbashi', 'Deuxième plus grande ville, centre industriel et minier important du Katanga.', 'Principale', 14),
('Tsévié', 'Ville située dans la région maritime, centre agricole important.', 'Principale', 15),
('Kassala', 'Ville située près de la frontière érythréenne, un important centre commercial.','Principale', 5),
('Ziguinchor', 'Ville portuaire située dans le sud du pays, importante pour le commerce et l’agriculture.', 'Principale', 16),
('Kismayo', 'Ville portuaire sur la mer d\'Arabie, un centre commercial majeur.','Principale', 6),
('Accra', 'Capitale du Ghana et plus grande ville du pays, centre économique et culturel.', 'Capitale', 13),
('Kara', 'Troisième ville du pays, située dans le nord, capitale de la région de Kara.', 'Principale', 15),
('Dire Dawa','Ville commerciale importante située à l\'est du pays.','Principale', 12),
('Le Caire', 'Le Caire est la plus grande ville arabe et l\'une des plus grandes villes du monde, avec une histoire ancienne qui remonte à l\'Égypte ancienne.','Capitale', 4),
('Enugu','Ville industrielle et centre administratif de l\'État d\'Enugu.','Principale', 9),
('Annaba', 'Ville portuaire et industrielle, avec un riche passé historique.','Principale', 3),
('Sharm el-Sheikh','Station balnéaire de la mer Rouge, populaire pour le tourisme.','Principale', 4),
('Fomboni', 'Ville principale de l\'île de Mohéli, plus petite mais importante culturellement.','Principale', 7),
('Bimbini','Ville côtière située sur l\'île d\'Anjouan.','Principale', 7),
('Tamale', 'Capitale de la région du Nord, centre de culture et commerce du nord du Ghana.', 'Principale', 13),
('Thiès', 'Ville industrielle et deuxième plus grande ville du pays, importante pour l’agriculture.', 'Principale', 16),
('Hargeisa', 'Ville principale de la région du Somaliland, importante pour l\'économie et la culture.','Principale', 6);
